### PR TITLE
Update dom query selectors

### PR DESCRIPTION
**Pull request by blaise-io**
The query selectors seem to be outdated.

### CODE REVIEW

**Comment by patrik-martinko** [comment]
I checked it and the used selectors are up-to-date and work for me. Next sibling is the button [data-testid="send-button"]. Do you have a different version of UI? What version of ChatGPT do you use?

**Comment by blaise-io** [comment]
I use https://chat.openai.com/?q=test, no subscription. I have this issue on Firefox: The click on the send button seems to be broken. The input box is correctly populated with the query. Now that I look at it again, it indeed does not seem to be the selectors. Maybe it's the button being disabled, and not enabled by the time the send button is clicked? 

This is the HTML I get (relevant part):
```html
<div class="overflow-hidden flex flex-col w-full flex-grow relative border border-black/10 gizmo:border-black/20 gizmo:dark:border-white/30 dark:border-gray-900/50 dark:text-white rounded-xl gizmo:rounded-2xl shadow-xs dark:shadow-xs dark:bg-gray-700 bg-white gizmo:dark:bg-gray-800 gizmo:shadow-[0_0_0_2px_rgba(255,255,255,0.95)] gizmo:dark:shadow-[0_0_0_2px_rgba(52,53,65,0.95)]">
    <textarea id="prompt-textarea" tabindex="0" data-id="root" style="max-height: 200px; height: 56px; overflow-y: hidden;" rows="1" placeholder="Send a message" class="m-0 w-full resize-none border-0 bg-transparent py-[10px] pr-10 focus:ring-0 focus-visible:ring-0 dark:bg-transparent md:py-4 md:pr-12 gizmo:md:py-3.5 gizmo:placeholder-black/50 gizmo:dark:placeholder-white/50 pl-3 md:pl-4"></textarea>
    <button disabled="" class="absolute p-1 rounded-md md:bottom-3 md:p-2 md:right-3 dark:hover:bg-gray-900 dark:disabled:hover:bg-transparent right-2 gizmo:dark:disabled:bg-white gizmo:disabled:bg-black gizmo:disabled:opacity-10 disabled:text-gray-400 enabled:bg-brand-purple gizmo:enabled:bg-black text-white gizmo:p-0.5 gizmo:border gizmo:border-black gizmo:rounded-lg gizmo:dark:border-white gizmo:dark:bg-white bottom-1.5 transition-colors disabled:opacity-40" data-testid="send-button">
        <span class="" data-state="closed">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="none" class="icon-sm m-1 md:m-0"><path d="M.5 1.163A1 1 0 0 1 1.97.28l12.868 6.837a1 1 0 0 1 0 1.766L1.969 15.72A1 1 0 0 1 .5 14.836V10.33a1 1 0 0 1 .816-.983L8.5 8 1.316 6.653A1 1 0 0 1 .5 5.67V1.163Z" fill="currentColor"></path></svg>
        </span>
    </button>
</div>
```

**Comment by patrik-martinko** [comment]
I checked it in Firefox (because I use Brave) and you are right, it doesn't work in Firefox because the button is disabled. The dispatched input event should enable it, but it doesn't in Firefox. I need to examine it.

**Comment by patrik-martinko** [comment]
I fixed it in Firefox in version 1.0.5.

**Pull request closed without merging**
